# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step to clear cached GitHub actions
      - name: Remove Cached Actions
        run: rm -rf $GITHUB_ACTIONS_CACHE  # Clears cached actions

      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build game
        run: npm run dendrynexus make-html -- --pretty

      - name: Copy game.json to output
        run: cp out/game.json out/html/

      # ✅ Explicitly upload artifact with correct version
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: out/html

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1  # Correct version!
        with:
          path: 'out/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Latest version
